POSTS_PER_PAGE = 10
LEN_OF_STR_METHOD_IN_POST = 15
SMALL_GIF = (b'\x47\x49\x46\x38\x39\x61\x02\x00'
             b'\x01\x00\x80\x00\x00\x00\x00\x00'
             b'\xFF\xFF\xFF\x21\xF9\x04\x00\x00'
             b'\x00\x00\x00\x2C\x00\x00\x00\x00'
             b'\x02\x00\x01\x00\x00\x02\x02\x0C'
             b'\x0A\x00\x3B')

GROUP_TITLE = 'Тестовая группа'
GROUP_TITLE_NEW = 'Новая тестовая группа'
GROUP_SLUG = 'test-slug'
GROUP_SLUG_NEW = 'test-slug-new'
GROUP_DESCRIPTION = 'Тестовое описание'
GROUP_DESCRIPTION_NEW = 'Новое тестовое описание группы'
POST_TEXT = 'Текст тестового поста'
POST_TEXT_NEW = 'Текст нового тестового поста'
USERNAME_AUTHOR = 'test_name_1'
USERNAME_NOT_AUTHOR = 'test_name_2'
USERNAME_NEW = 'test_name_2'
EMAIL_USER = 'test1@mail.ru'
EMAIL_USER_NEW = 'test2@mail.ru'
PASSWORD = 'test_pass'
COMMENT_TEXT = 'Текст комментария'

INDEX_TEMPLATE = 'posts/index.html'
CREATE_POST_TEMPLATE = 'posts/create_post.html'
GROUP_LIST_TEMPLATE = 'posts/group_list.html'
PROFILE_TEMPLATE = 'posts/profile.html'
POST_DETAIL_TEMPLATE = 'posts/post_detail.html'
UPDATE_POST_TEMPLATE = 'posts/create_post.html'
AUTHOR_TEMPLATE = 'about/author.html'
TECH_TEMPLATE = 'about/tech.html'
LOGOUT_TEMPLATE = 'users/logged_out.html'
SIGNUP_TEMPLATE = 'users/signup.html'
LOGIN_TEMPLATE = 'users/login.html'
PASS_RESET_FORM_TEMPLATE = 'users/password_reset_form.html'
PASS_RESET_DONE_TEMPLATE = 'users/password_reset_done.html'
PASS_RESET_CONFIRM_TEMPLATE = 'users/password_reset_confirm.html'
PASS_RESET_COMPLETE_TEMPLATE = 'users/password_reset_complete.html'
